### ISSUE TITLE
Sanitize images from API response data before saving as transient

### ISSUE THREAD

**Issue by kellenmace** [WebDevStudios/WDS-Instagram-Widget#4]
@themarcusbattle,

Can we sanitize the images on line 423 of `wds-instagram-widget.php` before saving to the DB? I'm not sure what that data looks like. If it's markup, maybe `wp_kses()` can be used to only allow <img> tags through.

This work can continue on the `feature/code-review-from-kellen` branch.

Thanks

**Comment by themarcusbattle** [comment]
I have updated the array for the individual image sizes to be sanitized properly. 

**Link**
I do not have a link to provide since this hasn't been approved to be merged into master.

**Screenshot**
No screenshot can be provided until this is approved so that I can push to master and provide one there. 

**Code Review**
As requested, this review is available in the branch feature/code-review-from-kellen. It is also available in the actual project repo as a pull request https://github.com/WebDevStudios/project-amy-herzog-designs/pull/64

**Next Steps**
@kellenmace once approved, I can move this code from this branch over to the AHD repo and commit to master. As a point of clarification/reminder, this branch is in the actual WDS-Instagram-widget project which is not apart of our repo. Our repo for this project contains a copy of it so that we're not using submodules.
